### ISSUE TITLE
Using the following files as input ends up in incompilable code

### ISSUE THREAD

**Issue by jkiddo** [botunge/hapi-fhir-forge-profile-converter#2]
[PatientTimeExtension.xml.txt](https://github.com/botunge/hapi-fhir-forge-profile-converter/files/96067/PatientTimeExtension.xml.txt)
[BookingTicket.xml.txt](https://github.com/botunge/hapi-fhir-forge-profile-converter/files/96068/BookingTicket.xml.txt)
[Patient Appointment.xml.txt](https://github.com/botunge/hapi-fhir-forge-profile-converter/files/96066/Patient.Appointment.xml.txt)

**Comment by ztlsir** [comment]
why must need "PatientTimeExtension.xml.txt" and "BookingTicket.xml.txt"?
@jkiddo
